### PR TITLE
chore: upgrade yarn to 3.5

### PR DESCRIPTION
**Pull request by intergalacticspacehighway**
# Test Plan
Try running `yarn install`

### CODE REVIEW

**Comment by hirbod** [comment]
Nice! You also upgrade locally, sometimes it has issues.
I did with `yarn set version 3.5.0`

**Review by hirbod — APPROVED** [review]
LGTM. I already upgraded my global version to 3.5.0 as well

**Comment by alantoa** [comment]
Not sure why those CI builds are failing.

**Comment by hirbod** [comment]
Hm, I mean we are already on yarn 3 but this sounds weird:
https://vercel.com/guides/does-vercel-support-yarn-2

**Comment by hirbod** [comment]
I created a new lock, lets see

**Comment by hirbod** [comment]
Ok, it passed now

**Review by alantoa — APPROVED** [review]
LGTM

**Pull request merged**
