### PR TITLE
Lazy loading

### PR DESCRIPTION
**Pull request by axeldelafosse**
# Why

The `First Load JS shared by all` is still pretty high (1 MB) so we need to reduce it

# How

- Lazy load WalletConnect provider
- Lazy load Ethers
- Remove unused code
- TODO: lazy load wagmi
- TODO: lazy load RainbowKit

# Test Plan

Run the apps and test the web3 actions

### CODE REVIEW

**Comment by intergalacticspacehighway** [comment]
not sure what's wrong but it's getting stuck on opening the app. I tried cleaning everything 😕 

https://user-images.githubusercontent.com/23293248/187599623-864e6e20-bb89-4216-be9a-4fdc57777d42.mov

**Comment by intergalacticspacehighway** [comment]
I think there's similar issue on vercel preview - https://showtime-git-feature-show2-1164-lazy-load-packages-showtime.vercel.app/

**Comment by intergalacticspacehighway** [comment]
i think this could be an issue. I don't know why rudderstack request is affecting this PR 😕 

Screenshot 2022-08-31 at 11 10 19 AM

**Comment by axeldelafosse** [comment]
https://github.com/showtime-xyz/showtime-frontend/pull/1459

**Pull request closed without merging**
