### PR TITLE
Update push notifications preferences

### PR DESCRIPTION
**Pull request by axeldelafosse**
# Why

We are about to enable push notifications so we want users to be able to update their preferences. This is the worst design but we don't have any design for it, and we don't have any copywriting. This PR is unblocking the release, let's revisit this screen with a designer

# How

- Added a tab in Settings
- Added some switches to enable / disable notifications

# Test Plan

While being logged in, go to your settings, check the "Push Notifications" tab and play with the switches

### CODE REVIEW

**Review by intergalacticspacehighway — APPROVED** [review]
LGTM ❇️

**Comment by alantoa** [comment]
waiting for my PRs, I'll do some improvements to UI.

**Comment by alantoa** [comment]
just found the list `item` and the `TabBar` has some bug, so fixed it.
now I think we need some copywriting, we can push it.
 
Before: 
image

After:  

https://user-images.githubusercontent.com/37520667/184908226-f862e07f-cd27-467c-954f-d46e1b0165cf.mov

**Review by alantoa — APPROVED** [review]
LGTM! ✨

**Pull request merged**
