### PR TITLE
remove haptics from tabs.

### PR DESCRIPTION
**Pull request by intergalacticspacehighway**
# Why
On android, it's kinda annoying. It vibrates.

### CODE REVIEW

**Review by alantoa — APPROVED** [review]
LGTM 😆

**Comment by hirbod** [comment]
On iOS it was kinda neat though :D
But yeah, we can remove it.

**Review by hirbod — APPROVED** [review]

**Comment by intergalacticspacehighway** [comment]
> On iOS it was kinda neat though :D

I think haptics should be used for some rewarding actions. Feels weird when it happens on tab presses. But let me know if you think otherwise.

**Comment by hirbod** [comment]
No, I absolutely agree. Showtime was the first app I used that had these interactions on Tabs, I liked it but I totally think you're right. For example, liking with a heart could trigger a Haptic

**Pull request merged**
