### PR TITLE
fix: audio compression for android

### PR DESCRIPTION
**Pull request by numandev1**
# Why
In Android, audio compression was working randomly

# How
i fixed in [react-native-compressor](https://github.com/numandev1/react-native-compressor) and just updated version in this PR

# Test Plan
you try to send audio in `useSendChannelMessage` on Android before and after this PR

### CODE REVIEW

**Comment by hirbod** [comment]
Hey @numandev1, thanks for providing a PR directly to our App. LGTM :)

**Review by hirbod — APPROVED** [review]

**Comment by intergalacticspacehighway** [comment]
Thanks for the PR @numandev1 ❤️

**Comment by hirbod** [comment]
@numandev1, actually, this PR broke our Android build.

```
> Task :react-native-compressor:compileDebugKotlin FAILED
e: file:///Users/hirbod/Github/showtime/showtime-frontend/node_modules/react-native-compressor/android/src/main/java/com/reactnativecompressor/Utils/Uploader.kt:8:8 Unresolved reference: io
e: file:///Users/hirbod/Github/showtime/showtime-frontend/node_modules/react-native-compressor/android/src/main/java/com/reactnativecompressor/Utils/Uploader.kt:9:8 Unresolved reference: io
e: file:///Users/hirbod/Github/showtime/showtime-frontend/node_modules/react-native-compressor/android/src/main/java/com/reactnativecompressor/Utils/Uploader.kt:47:27 Unresolved reference: ProgressHelper
e: file:///Users/hirbod/Github/showtime/showtime-frontend/node_modules/react-native-compressor/android/src/main/java/com/reactnativecompressor/Utils/Uploader.kt:47:70 Unresolved reference: ProgressUIListener
e: file:///Users/hirbod/Github/showtime/showtime-frontend/node_modules/react-native-compressor/android/src/main/java/com/reactnativecompressor/Utils/Uploader.kt:49:13 'onUIProgressStart' overrides nothing
e: file:///Users/hirbod/Github/showtime/showtime-frontend/node_modules/react-native-compressor/android/src/main/java/com/reactnativecompressor/Utils/Uploader.kt:50:23 Unresolved reference: onUIProgressStart
e: file:///Users/hirbod/Github/showtime/showtime-frontend/node_modules/react-native-compressor/android/src/main/java/com/reactnativecompressor/Utils/Uploader.kt:54:13 'onUIProgressChanged' overrides nothing
e: file:///Users/hirbod/Github/showtime/showtime-frontend/node_modules/react-native-compressor/android/src/main/java/com/reactnativecompressor/Utils/Uploader.kt:65:13 'onUIProgressFinish' overrides nothing
e: file:///Users/hirbod/Github/showtime/showtime-frontend/node_modules/react-native-compressor/android/src/main/java/com/reactnativecompressor/Utils/Uploader.kt:66:23 Unresolved reference: onUIProgressFinish
```

**Comment by numandev1** [comment]
@hirbod I check it after a while

**Pull request merged**
