### PR TITLE
fix: scroll restoration on web back/forward press

### PR DESCRIPTION
**Pull request by intergalacticspacehighway**
# Why
- Scroll position is not preserved when user passes back/forward button in browser.

# How
- Uses NextJS's experimental scrollRestoration flag that restores scroll on back/forward press. It requires the page height to be synchronously calculated.
- I added `minHeight` to InfiniteQueryList on web that uses `estimatedItemSize`. We're already using `estimatedItemSize` as it is required by `FlashList`. I think this could be good enough solution for now until it is resolved at Virtuoso.

# Test Plan
- Scroll position is restored on back/forward browser buttons.

https://user-images.githubusercontent.com/23293248/188635476-be5e52a7-e70b-4453-b45b-1ad17fcfc540.mov

https://user-images.githubusercontent.com/23293248/188636482-45b9c879-b707-46a7-860d-e3dbadc80017.mov

### CODE REVIEW

**Comment by intergalacticspacehighway** [comment]
will need to release InfiniteQueryList

**Comment by alantoa** [comment]
I just tested it, seems to not work, or is it need to wait for the new List release?

https://user-images.githubusercontent.com/37520667/188635426-24425ad0-f44a-422a-8ccb-d3ae43aa33d0.mov

**Comment by intergalacticspacehighway** [comment]
oh yes, we need to release new list. bit watch should work though!

**Review by alantoa — APPROVED** [review]
LGTM! 🔥

**Review by axeldelafosse — APPROVED** [review]
LFG ✨

**Pull request merged**
