### PR TITLE
fix: login stays open sometimes

### PR DESCRIPTION
**Pull request by intergalacticspacehighway**
# Why
- Noticed during spotify decoupled flow, login modal stayed open.
### Root cause
During login we do `router.push(/login)`. router.pop was being done in a callback that would be called in a useEffect post login. Leading to weird race conditions. 

# How
We make sure to call router.pop in login() function synchronously instead of useEffect. This makes sure it works well with our promise based await loginPromise(); await onboardingPromise() setup.

# Test Plan
- Test music drop decoupled flow

### CODE REVIEW

**Review by alantoa — APPROVED** [review]
LGTM! 
do we need to rebuild the native app?

**Review by hirbod — APPROVED** [review]
🔥

**Comment by intergalacticspacehighway** [comment]
> do we need to rebuild the native app?

we can do a codepush!

**Comment by hirbod** [comment]
> we can do a codepush!

I think we can't. Stage has some new native libraries. Maybe just cherry picking

**Pull request merged**
