### PR TITLE
fix: vscode auto import

### PR DESCRIPTION
**Pull request by alantoa**
# Why

When using automatic import in vscode, there is an issue where it adds the `packages/*` prefix when importing any component from the `packages/app/*` files.  

For example: auto import is `"packages/app/context/like-context";` ranther than `"app/context/like-context";`

# How 

Update ts `tsconfig.json` file. 

# Test Plan

### CODE REVIEW

**Review by hirbod — APPROVED** [review]

**Comment by hirbod** [comment]
Can we please also remove the rule which removes unused imports on save? It can warn, but it should not automatically remove. It is so annoying when copying stuff from one file to the other and it automatically removes stuff

**Review by intergalacticspacehighway — APPROVED** [review]
LGTM ❇️

**Comment by hirbod** [comment]
I pushed a change @alantoa, you can review. This will warn if we have unused imports but will not automatically remove them.

**Comment by alantoa** [comment]
@hirbod yeah, agreed with you!

**Comment by hirbod** [comment]
Ok, I can't describe how often it annoyed me :D

**Pull request merged**
